my.yog = TEST YOG
my.dis = TEST DIS

#Provide eureka location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register with Eureka (optional by default these are true )
eureka.client.register-with-eureka=true
# Enable Fetching other MS# Details
eureka.client.fetch-registry=true
spring.config.import=optional:configserver:http://localhost:8888
